# Generated by Django 4.1.5 on 2023-03-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_creditcard_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
