# Generated by Django 4.1.5 on 2023-03-22 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_creditcard_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='payment',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
