# Generated by Django 4.1.5 on 2023-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_creditcard_payment_creditcard_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
